name: Build and Push

on:
  push:
    branches:
      - main

  workflow_dispatch:
  
permissions:
  contents: write
  pages: write
  id-token: write
  
jobs:
  build:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run build script
        run: npm run build

      - name: Create .nojekyll file
        run: touch ./dist/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          clean: true
          folder: dist